#!/bin/bash
mkdir -p ./nodes

printf "%b" "#!/bin/bash

./bits/deploykeys/install

RAILS_NAME=samplerails \\
  RAILS_REPO=git@github.com:capbash/samplerails.git \\
  ./bits/rails/install
" > ./nodes/rails

chmod 755 ./nodes/rails

capbash install deploykeys
capbash install git
capbash install docker