#!/bin/bash
source ./submodules/bootstrap/logging
set -euo pipefail ; IFS=$'\n\t'

#-----------
# Configurations
#-----------

RAILS_NAME=${RAILS_NAME-samplerails}
RAILS_DIR=${RAILS_DIR-/var/local/apps/${RAILS_NAME}}
RAILS_REPO=${RAILS_REPO-git@github.com:aforward/samplerails.git}
RAILS_HTTP_PORT=${RAILS_PORT-80}

#-----------
# Install Script
#-----------

mkdir -p $RAILS_DIR

cp ./submodules/rails/files/rails.dockerfile $RAILS_DIR/Dockerfile
sed -i s/@ELIXIR_VERSION@/$ELIXIR_VERSION/g $RAILS_DIR/Dockerfile
sed -i s/@RAILS_NAME@/${RAILS_NAME}/g $RAILS_DIR/Dockerfile

GIT_URL=$RAILS_REPO \
  GIT_APPS_DIR=$RAILS_DIR \
  GIT_REPO_NAME=webapp \
  ./submodules/git/install

printf "%b" "
webapp/.git
webapp/.gitignore
webapp/test
webapp/README.md
" > $RAILS_DIR/.dockerignore

(cd $RAILS_DIR && docker build -t ${RAILS_NAME} .)

printf "%b" "#!/bin/bash
docker run -i -t -p 9873:3000 ${RAILS_NAME} /bin/bash
" > $RAILS_DIR/debug

printf "%b" "#!/bin/bash
docker rm ${RAILS_NAME} > /dev/num
docker run -d -t -p ${RAILS_HTTP_PORT}:3000 --name ${RAILS_NAME} ${RAILS_NAME}
" > $RAILS_DIR/start

NAME=$RAILS_NAME DIR=$RAILS_DIR ./submodules/docker/idempot
NAME=$RAILS_NAME DIR=$RAILS_DIR ./submodules/docker/stop

chmod 755 $RAILS_DIR/debug
chmod 755 $RAILS_DIR/start
